"""Step 0 audit: verify the core CLAUDE.md assumptions before any feature/model work.

Checks, per the "Open items" in CLAUDE.md:
  1. Schema + row counts of ranking.parquet / submitting.parquet.
  2. Null-count check: BLOCK_TIME_UTC_mvt and TAXITIME_SEC_mvt blanked on DEP,
     intact on ARR; MVT_TIME_UTC_mvt populated for DEP.
  3. Sanity of MVT_TIME_UTC_mvt - SCHED_TIME_UTC_mvt for DEP (schedule->takeoff gap).
  4. Leak audit: presence and behaviour of AOBT_3_flt / LOBT_flt / EOBT_1_flt /
     IOBT_flt relative to the (known) off-block time in TRAINING data, and their
     null rates for DEP rows in ranking.parquet.
  5. Date ranges of ranking vs training.

Run:  .venv/Scripts/python.exe src/ingest/audit_ranking.py
Writes a copy of the report to  reports/step0_audit.md
"""

from __future__ import annotations

import io
import os
from pathlib import Path

os.environ.setdefault("POLARS_UNKNOWN_EXTENSION_TYPE_BEHAVIOR", "load_as_storage")

import polars as pl

ROOT = Path(__file__).resolve().parents[2]
RANKING = ROOT / "data" / "ranking" / "ranking.parquet"
SUBMITTING = ROOT / "data" / "ranking" / "submitting.parquet"
TRAIN_GLOB = "data/raw/training_2025-*.parquet"
REPORT = ROOT / "reports" / "step0_audit.md"

BUF = io.StringIO()


def out(*args: object) -> None:
    line = " ".join(str(a) for a in args)
    print(line)
    BUF.write(line + "\n")


def hr(title: str) -> None:
    out(f"\n## {title}\n")


def null_table(df: pl.DataFrame, cols: list[str], group: str | None = None) -> pl.DataFrame:
    exprs = [pl.col(c).null_count().alias(c) for c in cols]
    if group is None:
        base = df.select(pl.len().alias("n_rows"), *exprs)
    else:
        base = df.group_by(group).agg(pl.len().alias("n_rows"), *exprs).sort(group)
    return base


def main() -> None:
    out(f"# Step 0 audit — {RANKING.name}")
    out(f"generated by src/ingest/audit_ranking.py")

    ranking = pl.read_parquet(RANKING)
    submitting = pl.read_parquet(SUBMITTING)

    hr("1. Shapes & schema")
    out(f"ranking.parquet    : {ranking.height:,} rows x {ranking.width} cols")
    out(f"submitting.parquet : {submitting.height:,} rows x {submitting.width} cols")
    out("\nranking schema:")
    for name, dt in ranking.schema.items():
        out(f"  {name:<24} {dt}")

    phase_counts = ranking.group_by("PHASE_mvt").len().sort("PHASE_mvt")
    out("\nPHASE_mvt breakdown:")
    out(phase_counts)

    dep = ranking.filter(pl.col("PHASE_mvt") == "DEP")
    arr = ranking.filter(pl.col("PHASE_mvt") == "ARR")

    hr("2. Null-count check (blanking invariant)")
    key_cols = [
        "MVT_TIME_UTC_mvt",
        "BLOCK_TIME_UTC_mvt",
        "SCHED_TIME_UTC_mvt",
        "TAXITIME_SEC_mvt",
        "RUNWAY_mvt",
        "STAND_mvt",
        "AIRCRAFT_TYPE_mvt",
    ]
    out("null counts by PHASE_mvt:")
    out(null_table(ranking, key_cols, group="PHASE_mvt"))

    out("\nExpectations:")
    dep_block_nulls = dep["BLOCK_TIME_UTC_mvt"].null_count()
    dep_taxi_nulls = dep["TAXITIME_SEC_mvt"].null_count()
    arr_block_nulls = arr["BLOCK_TIME_UTC_mvt"].null_count()
    arr_taxi_nulls = arr["TAXITIME_SEC_mvt"].null_count()
    dep_mvt_nulls = dep["MVT_TIME_UTC_mvt"].null_count()

    out(f"  DEP BLOCK_TIME_UTC_mvt null : {dep_block_nulls:,} / {dep.height:,}"
        f"  -> {'OK all blanked' if dep_block_nulls == dep.height else 'WARNING not fully blanked'}")
    out(f"  DEP TAXITIME_SEC_mvt  null : {dep_taxi_nulls:,} / {dep.height:,}"
        f"  -> {'OK all blanked' if dep_taxi_nulls == dep.height else 'WARNING not fully blanked'}")
    out(f"  ARR BLOCK_TIME_UTC_mvt null : {arr_block_nulls:,} / {arr.height:,}"
        f"  -> {'OK mostly intact' if arr_block_nulls < 0.1 * max(arr.height,1) else 'WARNING many nulls'}")
    out(f"  ARR TAXITIME_SEC_mvt  null : {arr_taxi_nulls:,} / {arr.height:,}"
        f"  -> {'OK mostly intact' if arr_taxi_nulls < 0.1 * max(arr.height,1) else 'WARNING many nulls'}")
    out(f"  DEP MVT_TIME_UTC_mvt  null : {dep_mvt_nulls:,} / {dep.height:,}"
        f"  -> {'OK takeoff time present' if dep_mvt_nulls < 0.05 * max(dep.height,1) else 'CRITICAL takeoff time missing — architecture assumption breaks'}")

    hr("3. Sanity: MVT_TIME_UTC_mvt - SCHED_TIME_UTC_mvt for DEP (minutes)")
    gap = dep.select(
        ((pl.col("MVT_TIME_UTC_mvt") - pl.col("SCHED_TIME_UTC_mvt")).dt.total_seconds() / 60.0)
        .alias("gap_min")
    ).drop_nulls()
    if gap.height:
        q = gap.select(
            pl.col("gap_min").min().alias("min"),
            pl.col("gap_min").quantile(0.01).alias("p01"),
            pl.col("gap_min").quantile(0.10).alias("p10"),
            pl.col("gap_min").median().alias("p50"),
            pl.col("gap_min").quantile(0.90).alias("p90"),
            pl.col("gap_min").quantile(0.99).alias("p99"),
            pl.col("gap_min").max().alias("max"),
            pl.col("gap_min").mean().alias("mean"),
        )
        out(q)
        out("expected: p50 roughly 15-25 min, long right tail, few large negatives")
    else:
        out("no non-null rows for this gap — investigate")

    hr("4. Leak audit — flight-list off-block columns")
    leak_cols = ["LOBT_flt", "IOBT_flt", "EOBT_1_flt", "AOBT_3_flt", "ARVT_1_flt", "ARVT_3_flt"]
    out("null counts by PHASE_mvt (ranking.parquet):")
    out(null_table(ranking, leak_cols, group="PHASE_mvt"))

    out("\nDEP-row non-null fraction (ranking):")
    for c in leak_cols:
        frac = 1.0 - dep[c].null_count() / max(dep.height, 1)
        out(f"  {c:<12} {frac:6.1%} present")

    # Behaviour vs true off-block, measured on TRAINING data (where BLOCK_TIME_UTC_mvt is intact).
    out("\n--- training data: how closely do these track the true off-block time? ---")
    train = pl.scan_parquet(str(ROOT / TRAIN_GLOB))
    tdep = (
        train.filter(pl.col("PHASE_mvt") == "DEP")
        .select(["BLOCK_TIME_UTC_mvt", *leak_cols])
        .collect()
    )
    out(f"training DEP rows: {tdep.height:,}")
    ref = pl.col("BLOCK_TIME_UTC_mvt")
    for c in ["LOBT_flt", "IOBT_flt", "EOBT_1_flt", "AOBT_3_flt"]:
        d = tdep.select(
            ((pl.col(c) - ref).dt.total_seconds() / 60.0).alias("d_min")
        ).drop_nulls()
        if not d.height:
            out(f"  {c:<12} no overlap")
            continue
        stats = d.select(
            pl.col("d_min").median().alias("median_min"),
            pl.col("d_min").quantile(0.10).alias("p10"),
            pl.col("d_min").quantile(0.90).alias("p90"),
            (pl.col("d_min").abs() <= 1).mean().alias("within_1min"),
            (pl.col("d_min").abs() <= 5).mean().alias("within_5min"),
        )
        row = stats.row(0, named=True)
        cov = d.height / tdep.height
        flag = "  <-- TRACKS off-block closely (potential leak)" if row["within_5min"] > 0.8 else ""
        out(f"  {c:<12} coverage={cov:5.1%}  median={row['median_min']:+.1f}m  "
            f"p10={row['p10']:+.1f}  p90={row['p90']:+.1f}  "
            f"|d|<=1m={row['within_1min']:.1%}  |d|<=5m={row['within_5min']:.1%}{flag}")

    out("\nNote: AOBT_3_flt is the actual off-block time from the flown trajectory.")
    out("If it is present for ranking DEP rows AND tracks BLOCK_TIME_UTC_mvt within minutes,")
    out("the target is directly recoverable — build it as a toggleable feature block (per CLAUDE.md).")

    hr("4b. Leak strength — naive taxi = MVT_TIME_UTC_mvt - AOBT_3_flt (training)")
    naive = tdep.select(
        pl.col("BLOCK_TIME_UTC_mvt"),
        pl.col("AOBT_3_flt"),
    )
    # bring MVT_TIME back in from training
    tnaive = (
        train.filter(pl.col("PHASE_mvt") == "DEP")
        .select(
            (pl.col("MVT_TIME_UTC_mvt") - pl.col("BLOCK_TIME_UTC_mvt")).dt.total_seconds().alias("taxi_true"),
            (pl.col("MVT_TIME_UTC_mvt") - pl.col("AOBT_3_flt")).dt.total_seconds().alias("taxi_aobt3"),
        )
        .drop_nulls()
        .collect()
    )
    e = (tnaive["taxi_aobt3"] - tnaive["taxi_true"])
    rmse = (e.pow(2).mean()) ** 0.5
    out(f"rows                : {tnaive.height:,}")
    out(f"true taxi std       : {tnaive['taxi_true'].std():.1f} s   (RMSE of predicting the mean)")
    out(f"naive-AOBT3 RMSE    : {rmse:.1f} s")
    out(f"naive-AOBT3 MAE     : {e.abs().mean():.1f} s")
    out(f"bias (median / mean): {e.median():.1f} / {e.mean():.1f} s")
    out(f"|err| <= 60s        : {(e.abs() <= 60).mean():.1%}")
    out(f"|err| <= 120s       : {(e.abs() <= 120).mean():.1%}")
    out("verdict: AOBT_3_flt is a STRONG FEATURE, not a clean leak — it is a noisier,")
    out("biased second measurement of off-block. Use in a toggleable feature block.")

    hr("5. Date ranges")
    for label, df in [("ranking", ranking)]:
        rng = df.select(
            pl.col("MVT_TIME_UTC_mvt").min().alias("mvt_min"),
            pl.col("MVT_TIME_UTC_mvt").max().alias("mvt_max"),
            pl.col("SCHED_TIME_UTC_mvt").min().alias("sched_min"),
            pl.col("SCHED_TIME_UTC_mvt").max().alias("sched_max"),
        )
        out(f"{label}:")
        out(rng)
    months = ranking.select(
        pl.col("MVT_TIME_UTC_mvt").dt.strftime("%Y-%m").alias("ym")
    ).group_by("ym").len().sort("ym")
    out("ranking rows per year-month (MVT_TIME_UTC_mvt):")
    out(months)

    hr("6. Airports present in ranking (ADEP for DEP)")
    out(dep.group_by("ADEP_mvt").len().sort("len", descending=True))
    out("\nNote: CLAUDE.md lists 11 airports but LTAI (Antalya) has NO departures in")
    out("training or ranking — arrivals only. The DEP prediction target covers 10 airports.")

    hr("7. Submission template alignment")
    sub_ids = set(submitting["MVT_ID_mvt"].to_list())
    dep_ids = set(dep["MVT_ID_mvt"].to_list())
    out(f"submitting MVT_ID_mvt count      : {len(sub_ids):,}")
    out(f"ranking DEP MVT_ID_mvt count     : {len(dep_ids):,}")
    out(f"submitting ids not in ranking DEP: {len(sub_ids - dep_ids):,}")
    out(f"ranking DEP ids not in submitting: {len(dep_ids - sub_ids):,}")
    out(f"submitting TAXITIME_SEC_mvt non-null: {submitting['TAXITIME_SEC_mvt'].drop_nulls().len():,}"
        " (expected 0 — it's a blank template)")

    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text(BUF.getvalue(), encoding="utf-8")
    out(f"\nreport written to {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
