"""Stage 1 validation on 2025 truth (CLAUDE.md "Open items" — do this first).

For each airport measure:
  - link rate            : departures paired to an inbound (A_own found)
  - has-next rate         : departures with an A_next (upper side of L)
  - binding rate          : fraction where L > 0 actually constrains
  - violation rate        : fraction where the TRUE off-block falls outside [L, U]
  - median interval U-L   : vs the marginal sd of taxi
  - truncation gain       : RMSE of a per-airport-mean predictor, before vs after
                            clamping to [L, U] on confidently linked rows

Decision rule from CLAUDE.md: violation rate > ~10% for an airport means towing
has corrupted the alignment there -> demote its bounds to soft features.

Run:  .venv/Scripts/python.exe src/link/validate_links.py
Writes reports/stage1_link_validation.md
"""

from __future__ import annotations

import io
import os
from pathlib import Path

os.environ.setdefault("POLARS_UNKNOWN_EXTENSION_TYPE_BEHAVIOR", "load_as_storage")

import polars as pl

from stand_link import build_stand_links  # noqa: E402  (run as script from src/link)

ROOT = Path(__file__).resolve().parents[2]
TRAIN_GLOB = str(ROOT / "data" / "raw" / "training_2025-*.parquet")
REPORT = ROOT / "reports" / "stage1_link_validation.md"

BUF = io.StringIO()


def out(*a: object) -> None:
    line = " ".join(str(x) for x in a)
    print(line)
    BUF.write(line + "\n")


def main() -> None:
    out("# Stage 1 — stand linking validation on 2025 truth\n")
    out("generated by src/link/validate_links.py")

    cols = [
        "MVT_ID_mvt", "FLIGHT_ID_mvt", "PHASE_mvt", "ADEP_mvt", "ADES_mvt",
        "MVT_TIME_UTC_mvt", "BLOCK_TIME_UTC_mvt", "SCHED_TIME_UTC_mvt",
        "AIRCRAFT_TYPE_mvt", "AIRCRAFT_TYPE_flt", "RUNWAY_mvt", "STAND_mvt",
        "TAXITIME_SEC_mvt",
    ]
    df = pl.read_parquet(TRAIN_GLOB, columns=cols)
    out(f"\nloaded {df.height:,} movements "
        f"({df.filter(pl.col('PHASE_mvt') == 'DEP').height:,} DEP / "
        f"{df.filter(pl.col('PHASE_mvt') == 'ARR').height:,} ARR)")

    # Truth table for departures (kept separate from the split-blind builder input).
    truth = (
        df.filter(pl.col("PHASE_mvt") == "DEP")
        .select(
            "MVT_ID_mvt",
            true_taxi="TAXITIME_SEC_mvt",
            true_offblock="BLOCK_TIME_UTC_mvt",
        )
    )

    # Split-blind view: blank the departure off-block + taxi before linking.
    blind = df.with_columns(
        pl.when(pl.col("PHASE_mvt") == "DEP")
        .then(None)
        .otherwise(pl.col("BLOCK_TIME_UTC_mvt"))
        .alias("BLOCK_TIME_UTC_mvt"),
        pl.when(pl.col("PHASE_mvt") == "DEP")
        .then(None)
        .otherwise(pl.col("TAXITIME_SEC_mvt"))
        .alias("TAXITIME_SEC_mvt"),
    )

    links = build_stand_links(blind)
    out(f"built links for {links.height:,} departures")

    j = links.join(truth, on="MVT_ID_mvt", how="inner").filter(
        pl.col("true_taxi").is_not_null()
        & pl.col("true_taxi").is_between(0, 4 * 3600)
    )
    out(f"joined to truth (0 <= taxi <= 4h): {j.height:,} rows")

    linked = j.filter(pl.col("link_confidence") != "none")
    j = j.with_columns(
        in_bounds=(
            (pl.col("true_taxi") >= pl.col("L_sec") - 60)
            & (pl.col("true_taxi") <= pl.col("U_sec") + 60)
        ),
        viol_high=pl.col("true_taxi") > pl.col("U_sec") + 60,   # true off-block < A_own
        viol_low=pl.col("true_taxi") < pl.col("L_sec") - 60,    # true off-block > A_next
    )

    overall_sd = float(j["true_taxi"].std())
    out(f"\nmarginal sd of true taxi (linked-eligible rows): {overall_sd:.1f} s")

    # ---------------------------------------------------------------- per airport
    out("\n## Per-airport metrics\n")
    hdr = (f"{'airport':<8} {'n_dep':>8} {'link%':>7} {'next%':>7} "
           f"{'bind%':>7} {'viol%':>7} {'vHi%':>6} {'vLo%':>6} "
           f"{'medU-L':>8} {'med/sd':>7} {'verdict':>8}")
    out(hdr)
    out("-" * len(hdr))

    airports = sorted(j["airport"].unique().to_list())
    summary_rows = []
    for ap in airports:
        a = j.filter(pl.col("airport") == ap)
        n = a.height
        a_link = a.filter(pl.col("link_confidence") != "none")
        link_rate = a_link.height / n
        next_rate = a["has_next"].mean()
        bind_rate = a_link["bound_binding"].mean() if a_link.height else 0.0

        # violations measured on linked rows only
        conf = a_link
        viol = float((conf["viol_high"] | conf["viol_low"]).mean()) if conf.height else 0.0
        vhi = float(conf["viol_high"].mean()) if conf.height else 0.0
        vlo = float(conf["viol_low"].mean()) if conf.height else 0.0
        med_int = float(conf["interval_sec"].median()) if conf.height else float("nan")
        med_sd = med_int / overall_sd if conf.height else float("nan")

        verdict = "HARD" if viol <= 0.10 else "SOFT"
        out(f"{ap:<8} {n:>8,} {link_rate:>6.1%} {float(next_rate):>6.1%} "
            f"{float(bind_rate):>6.1%} {viol:>6.1%} {vhi:>5.1%} {vlo:>5.1%} "
            f"{med_int:>8.0f} {med_sd:>7.2f} {verdict:>8}")
        summary_rows.append((ap, n, link_rate, viol, verdict))

    # -------------------------------------------------------- by confidence tier
    out("\n## By link-confidence tier (all airports)\n")
    out(f"{'tier':<6} {'n':>9} {'share':>7} {'bind%':>7} {'in[L,U]%':>9} "
        f"{'viol%':>7} {'medU-L':>8}")
    for tier in ["high", "med", "low", "none"]:
        t = j.filter(pl.col("link_confidence") == tier)
        if not t.height:
            continue
        share = t.height / j.height
        if tier == "none":
            out(f"{tier:<6} {t.height:>9,} {share:>6.1%} {'-':>7} {'-':>9} {'-':>7} {'-':>8}")
            continue
        out(f"{tier:<6} {t.height:>9,} {share:>6.1%} "
            f"{float(t['bound_binding'].mean()):>6.1%} "
            f"{float(t['in_bounds'].mean()):>8.1%} "
            f"{float((t['viol_high'] | t['viol_low']).mean()):>6.1%} "
            f"{float(t['interval_sec'].median()):>8.0f}")

    # --------------------------------------------------- truncation gain (proxy)
    out("\n## Truncation gain — per-airport-mean predictor clamped to [L, U]\n")
    ap_mean = (
        j.group_by("airport")
        .agg(pl.col("true_taxi").mean().alias("ap_mean"))
    )
    hi = (
        j.join(ap_mean, on="airport")
        .filter(pl.col("link_confidence") == "high")
        .with_columns(
            clamped=pl.col("ap_mean").clip(pl.col("L_sec"), pl.col("U_sec"))
        )
    )
    if hi.height:
        def _rmse(d: pl.DataFrame, a: str, b: str) -> float:
            return float(((d[a] - d[b]).pow(2).mean()) ** 0.5)

        changed = hi.filter(pl.col("ap_mean") != pl.col("clamped"))
        binding = hi.filter(pl.col("bound_binding"))
        out(f"high-confidence rows: {hi.height:,}")
        out(f"RMSE  per-airport mean          : {_rmse(hi, 'ap_mean', 'true_taxi'):.1f} s")
        out(f"RMSE  clamped to [L, U]         : {_rmse(hi, 'clamped', 'true_taxi'):.1f} s")
        out(f"rows the clamp actually changes : {changed.height:,} "
            f"({changed.height / hi.height:.3%})")
        out(f"rows where L > 0 (binding)      : {binding.height:,} "
            f"({binding.height / hi.height:.1%})")
        if binding.height:
            import numpy as np

            corr = float(
                np.corrcoef(binding["L_sec"], binding["true_taxi"])[0, 1]
            )
            out(f"  among binding: mean L={binding['L_sec'].mean():.0f}s  "
                f"mean taxi={binding['true_taxi'].mean():.0f}s  corr(L,taxi)={corr:.2f}")
        out(f"median ground time (inbound in-block -> est off-block): "
            f"{hi['ground_time_sec'].median():.0f} s")
        out("\n=> interval bounds do NOT constrain the prediction: median U-L "
            f"({hi['interval_sec'].median():.0f}s) is ~{hi['interval_sec'].median() / overall_sd:.0f}x "
            "the taxi sd, driven by ground time >> taxi variability. "
            "Truncated-mean (Stage 4) yields no gain here. Keep the linkage for "
            "ROTATION FEATURES (inbound delay, ground time, inbound type); "
            "use L only as a soft feature.")

    # ------------------------------------------------------------------- verdict
    out("\n## Verdict\n")
    hard = [r[0] for r in summary_rows if r[4] == "HARD"]
    soft = [r[0] for r in summary_rows if r[4] == "SOFT"]
    out(f"HARD bounds (violation <= 10%): {', '.join(hard) or 'none'}")
    out(f"SOFT bounds (violation  > 10%): {', '.join(soft) or 'none'}")
    tot_link = sum(r[1] * r[2] for r in summary_rows) / sum(r[1] for r in summary_rows)
    out(f"overall link rate: {tot_link:.1%}")

    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text(BUF.getvalue(), encoding="utf-8")
    out(f"\nreport written to {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
